service: popl-sp-api-fivetran

provider:
  name: google
  stage: dev
  runtime: python39
  region: us-central1
  project: stitch-bytecode

frameworkVersion: '2'
plugins:
  - serverless-google-cloudfunctions
  - serverless-dotenv-plugin
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - .env

functions:
  amazon-sp-api:
    handler: handler
    events:
      - http: path
