apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: popl-firebase-exctractor
spec:
  template:
    spec:
      timeoutSeconds: 3600
      serviceAccountName: firebase-extractor@poplco.iam.gserviceaccount.com
      containers:
      - image: gcr.io/stitch-bytecode/popl-firebase-extractor:latest
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi