service: popl-fivetran-api

provider:
  name: google
  stage: prod
  runtime: python39
  region: us-central1
  timeout: 120s
  project: poplco
  credentials: ~/.gcloud/popl/keyfile.json

frameworkVersion: '2'
plugins:
  - serverless-google-cloudfunctions
  - serverless-dotenv-plugin
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - .env

functions:
  amazon-sp:
    handler: amazon_sp_handler
    events:
      - http: path
  rakuten-smartfill:
    handler: rakuten_handler
    events:
      - http: path
