apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: popl-firebase-to-gcp-bucket
spec:
  template:
    spec:
      containers:
      - image: gcr.io/stitch-bytecode/firebase-to-gcp-bucket:latest
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
      timeoutSeconds: 0